global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.92.133','172.31.80.106:9100','172.31.95.38:9100',]
